---
backend: pacman

skip_if_no_internet: false
update_db: true
update_system: false

operations:
  - install:
      - grub
      - os-prober
      - efitools
  - remove:
      - calamares
      - archinstall
      - mkinitcpio-archiso
