# pacman.conf custom para Nexa OS Archiso Build

[options]
HoldPkg     = pacman systemd
Architecture = auto

Color
ILoveCandy
VerbosePkgLists
ParallelDownloads = 5

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# REPOSITÓRIOS OFICIAIS

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# Repositório de compatibilidade de 32 bits (Essencial para Steam, Proton e Wine)
[multilib]
Include = /etc/pacman.d/mirrorlist

# Repositório Chaotic-AUR (Kernels otimizados, Proton-GE e ferramentas de jogos pré-compilados)
# Para habilitá-lo no build final, as chaves do Chaotic-AUR devem estar presentes no chaveiro do host de build.
#[chaotic-aur]
#Server = https://cdn-mirror.chaotic.cx/chaotic-aur/$arch
