# pacman.conf custom para Nexa OS Archiso Build

[options]
HoldPkg     = pacman systemd
Architecture = auto

Color
ILoveCandy
VerbosePkgLists
ParallelDownloads = 5

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# REPOSITÓRIOS OFICIAIS

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# Repositório de compatibilidade de 32 bits (Essencial para Steam, Proton e Wine)
[multilib]
Include = /etc/pacman.d/mirrorlist

# Chaotic-AUR — Repositório binário de pacotes AUR pré-compilados.
# Mantido pela comunidade Arch. Utilizado por Garuda Linux, CachyOS e outras distros.
# Fornece: calamares, ags (Aylur's Gtk Shell), python-uvicorn e centenas de outros pacotes AUR.
[chaotic-aur]
SigLevel = DatabaseNever
Include = /etc/pacman.d/chaotic-mirrorlist
