# ==============================================================================
#  NEXA OS - SDDM THEME METADATA (nexa-sddm)
#  Salvar em: airootfs/usr/share/sddm/themes/nexa-sddm/theme.conf
# ==============================================================================

[General]
Name=Nexa OS Minimalist Login
Description=Tema QML de login estilo macOS Killer / glassmorphic para o Nexa OS
Author=Nexa Solutions
Version=1.0
Type=sddm-theme
ConfigFile=Main.qml
Background=background.png
